apiVersion: apps/v1
kind: Deployment
metadate:
  name: my-deployment
spec:
  replicas: 2
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: jenkins:latest
  template:
    metadata:
      labels:
        app: jenkins:latest
    spec:
      hostNetwork: true
      containers:
      - name: my-web
        image: jenkins:latest
        ports:
        - containerPort: 80