apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-first-rs
  labels:
    version: 0.0.1
spec:
  replicas: 2
  selector:
    matchLabels:
      project: My-project
      ver: 0.1
  template:
    metadata:
     # labels:
      #  project: My-project
       # ver: 0.1
      name: my-first-pod
      labels:
        project: My-project
        ver: 0.1
    spec:
      containers:
      - name: my-pod-for-rs
        image: nginx
        ports:
        - containerPort: 80
  